"""Stable SDK CLI exit codes."""

from enum import IntEnum


class ExitCode(IntEnum):
    SUCCESS = 0
    GATE_FAILURE = 1
    INVALID_ARGUMENTS = 2
    PROVIDER_EXECUTION_FAILURE = 3
    PROVIDER_REPORT_FAILURE = 4
    ARTIFACT_VALIDATION_FAILURE = 5
    UNRESOLVED_STRICT_CONTRACT = 6
    INTERNAL_ERROR = 7
    INCOMPATIBLE_VERSION = 8
    OPERATIONAL_LIMIT_EXCEEDED = 9
