#!/usr/bin/env python3
"""Generate commit-bound validation evidence (AUD-007).

Replaces the previously static, hand-maintained MANIFEST.md / VALIDATION_REPORT.json
(which drifted from the tree and carried no commit identity) with evidence
generated from the actual repository state:

- MANIFEST.md: inventory of every git-tracked file with its sha256, so the
  manifest cannot go stale (CI drift-checks it with `git diff --exit-code`).
- VALIDATION_REPORT.json: commit SHA, generation time, Python/tool/dependency
  versions, the exact gate commands CI runs, file count, and a file-tree digest.

This records verifiable facts only; it does NOT assert that the gates passed —
that is proven by the CI job (ci.yml) succeeding before this runs. Run:

    python scripts/generate_validation_report.py
"""

from __future__ import annotations
import hashlib
import json
import subprocess
import sys
from importlib.metadata import PackageNotFoundError, version
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
MANIFEST_PATH = REPO_ROOT / "MANIFEST.md"
REPORT_PATH = REPO_ROOT / "VALIDATION_REPORT.json"
# Files excluded from the inventory: the generated evidence files themselves
# (self-reference would make the digest unstable).
SELF_GENERATED = {"MANIFEST.md", "VALIDATION_REPORT.json"}

# The exact gate commands CI runs (AUD-008). Recorded as evidence, not executed
# here.
GATE_COMMANDS = [
    "python -m compileall l9_ci",
    "python -m ruff check l9_ci tests scripts",
    "python -m ruff format --check l9_ci tests scripts",
    "python -m mypy",
    "python -m pytest --cov=l9_ci --cov-branch",
]

RUNTIME_DEPENDENCIES = ["jsonschema", "referencing", "PyYAML"]
TOOLCHAIN = ["ruff", "mypy", "pytest", "pytest-cov", "coverage"]


def _git(*args: str) -> str:
    return subprocess.run(
        ["git", "-C", str(REPO_ROOT), *args],
        capture_output=True,
        text=True,
        check=True,
    ).stdout.strip()


def _tracked_files() -> list[str]:
    files = _git("ls-files").splitlines()
    return sorted(f for f in files if f not in SELF_GENERATED)


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _versions(names: list[str]) -> dict[str, str]:
    resolved: dict[str, str] = {}
    for name in names:
        try:
            resolved[name] = version(name)
        except PackageNotFoundError:
            resolved[name] = "not-installed"
    return resolved


def build_manifest(files: list[str], digests: dict[str, str]) -> str:
    lines = [
        "# Manifest",
        "",
        "Generated by `scripts/generate_validation_report.py`. Do not edit by "
        "hand — CI regenerates and drift-checks this file (AUD-007).",
        "",
        f"Files: {len(files)}",
        "",
        "| sha256 | path |",
        "|---|---|",
    ]
    lines.extend(f"| `{digests[f]}` | `{f}` |" for f in files)
    lines.append("")
    return "\n".join(lines)


def build_report(files: list[str], digests: dict[str, str]) -> dict[str, object]:
    # Deterministic file-tree digest: sha256 over "sha256␣path\n" lines.
    tree = "".join(f"{digests[f]} {f}\n" for f in files)
    file_tree_digest = hashlib.sha256(tree.encode("utf-8")).hexdigest()
    return {
        "schema": "l9.validation-report/v2",
        "repository": "Quantum-L9/l9-ci-sdk",
        "commit": _git("rev-parse", "HEAD"),
        "commit_committed_at": _git("show", "-s", "--format=%cI", "HEAD"),
        "generated_by": "scripts/generate_validation_report.py",
        "validated_by": ".github/workflows/ci.yml",
        # major.minor only — patch level varies across runners and is not part
        # of the reproducible commit-bound identity.
        "python_version": ".".join(sys.version.split()[0].split(".")[:2]),
        "toolchain_versions": _versions(TOOLCHAIN),
        "dependency_versions": _versions(RUNTIME_DEPENDENCIES),
        "gate_commands": GATE_COMMANDS,
        "file_count": len(files),
        "file_tree_digest": file_tree_digest,
    }


def main() -> int:
    files = _tracked_files()
    digests = {f: _sha256(REPO_ROOT / f) for f in files}
    MANIFEST_PATH.write_text(build_manifest(files, digests), encoding="utf-8")
    report = build_report(files, digests)
    REPORT_PATH.write_text(
        json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    print(f"wrote {MANIFEST_PATH.name} ({len(files)} files) and {REPORT_PATH.name}")
    print(f"commit={report['commit']} file_tree_digest={report['file_tree_digest']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
